### ISSUE TITLE
[Feature Request]:  Make the css for the client much prettier

### ISSUE THREAD

**Issue by JayPi4c** [schlunzis/Kurtama#133]
### What should be implemented?

The client just looks stupid now. CHANGE THAT !!1!!1111!!1!

**Comment by Til7701** [comment]
Do we want to use this list view? [https://dlsc.com/2017/09/07/javafx-tip-28-pretty-list-view/](https://dlsc.com/2017/09/07/javafx-tip-28-pretty-list-view/)

**Comment by JayPi4c** [comment]
Der aktuelle Stand sieht schon richtig gut aus!!

**Comment by Til7701** [comment]
Die Funktion der hinzugefügten UI Elemente würde ich in andere Issues auslagern. Außerdem habe ich noch auf dem Plan:

1. Ich würde gerne die Listen noch etwas einfacher zu sehen machen.
2. Die Lobby Liste könnte eine Tabelle werden. Diese hätte Spalten für Passwort und Anzahl der Spieler in der Lobby.
3. Den Create Lobby Dialog würde ich gerne vermeiden. Vielleicht könnte der Create Lobby Button mit einer schönen Animation durch die nötigen Felder ersetzt werden.
4. Vielleicht noch was in der Lobby anpassen. Da kenne ich gerade nicht den Stand.

**Comment by Til7701** [comment]
2 und 3 würde ich in andere issues auslagern. Du kannst dich auch gerne auf dem Branch austoben.
