### ISSUE TITLE
[Feature Request]: Lobby search

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#147]
### What should be implemented?

Filter the lobby list according to the content of the search text box

**Comment by JayPi4c** [comment]
We do have multiple options to tackle this issue:
using `controlsfx` we can introduce a `SearchableComboBox`:
![image](https://github.com/schlunzis/Kurtama/assets/32594337/f55a51a3-9b3d-4441-ba16-562a2e505c5a)
It's easy to implement and use but I think it would look nicer, if we keep the design as is and introduce a manual search functionality to the search lobby textfield.
