### ISSUE TITLE
Message Identification

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#17]
Ich habe folgendes Problem. Wenn eine Nachricht vom Server kommt wird diese vom [ClientMessageDispatcher](https://github.com/schlunzis/Kurtama/blob/develop/server/src/main/java/de/schlunzis/server/net/ClientMessageDispatcher.java) auf den EventBus gepostet. An dieser Stelle geht die Information über die Session, bzw. den User, welcher die Nachricht gesendet hat, verloren. Um eine Nachricht gezielt zurücksenden zu können, muss diese Information allerdings mit auf den EventBus gegeben werden. Folgende Lösungen kann ich mir vorstellen. (Vielleicht haben wir das schon mal diskutiert?)
1. Die ClientMessage im common bekommt eine AbstractClientMessage, welche ein Feld für die Session hat.
2. Wir machen im Server für jede Message aus dem common ein Event, welches die Message und die Session kapselt. (Viel extra Aufwand)
3. Wir machen im Server eine Klasse, welche die Beiden kapselt. Da würden wir aber das Pattern-Matching des EventBus wegwerfen. (nicht praktikabel)

Wie man vielleicht sieht, bin ich für Option 1.

**Comment by JayPi4c** [comment]
Ich sehe das Problem. Ich bin mir nur nicht so sicher, ob die Session in eine AbstractClientMessage passt. Ich bin mir nicht mehr sicher, aber wird die Session auch im Client gebraucht oder ob das nur serverseitig ist. Da ich die Session nur im Server sehe, denke ich mal, dass es bessere wäre, die Message nicht zu überfüllen und eher im Server dann einen Wrapper für die ankommenden Messages zu machen, einen `ClientMessageWrapper` oder so und den dann mit Meta-daten und weiteren Informationen zu füllen, wie beispielsweise der Session. Ich würde da mal das Thema Decorator Pattern in den Raum werfen. Vielleicht kann man da ja was praktisches finden.

**Comment by Til7701** [comment]
Wir könnten den ClassMatchingEventBus nehmen. Damit können wir Serverseitig einen Wrapper für alle Messages haben, welcher generisch die Messages zurückgibt. Der Wrapper kann dann auch die Session bereitstellen.

**Comment by Til7701** [comment]
siehe branch
