### ISSUE TITLE
[Feature Request]: Display version in Client

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#173]
### What should be implemented?

Display the current version in the client. Additionally, the server could inform the client about its version.

**Comment by JayPi4c** [comment]
I like the first part of this issue very much. Starting the client and knowing immediately what version is running will help us debug stuff much faster.
Concerning the second part: I think we should first come up with a stable process on how we do the versioning and what we consider breaking changes. Informing the client is one thing but in my eyes, it comes with the direct task of checking for compatibility. This can only be done easily, when we have a clear definition of what versions are compatible. This might be concluded directly from the semver rules.
