### ISSUE TITLE
Update to Java 23

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#279]
22 is now EOL. 23 released today.

**Comment by JayPi4c** [comment]
deb packages of jdk 23 may be downloaded from [here](http://launchpad.net/ubuntu/+source/openjdk-23)

**Comment by JayPi4c** [comment]
The update progress has to be delayed until there is a docker image that provides maven with jdk 23.
Currently, there is no image `maven:3.9.9-eclipse-temurin-23-alpine` yet.
