### ISSUE TITLE
[Feature Request]: Dialogs

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#52]
### What should be implemented?

Make a framework with FXWeaver to make it easy to add Dialogs with a custom return type.

**Comment by JayPi4c** [comment]
The Dialog does not need to have a return type but rather it should post Messages on the eventBus
https://github.com/rgielen/javafx-weaver/blob/master/samples/springboot-sample/src/main/java/net/rgielen/fxweaver/samples/springboot/controller/DialogController.java
