### ISSUE TITLE
[BUG]: Handle login of an already logged in user

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#78]
### What happened?

I can log into multiple client with one user

### Steps to reproduce

1. Start two clients
2. log into both with the same user

### Expected behaviour

One of the following:

1. The first logged in client should be logged out
2. The second one should not be allowed to log in (not a good idea)

### Actual behaviour

In the server the session for the user is overwritten. Thus the first client cannot do a lot of things. Notable not log out.

### Further Information

nothing

### Version

1.0-SNAPSHOT

### What OS are you using

NixOS

**Comment by JayPi4c** [comment]
Verstehe ich das richtig? Wenn ein User versucht, sich ein zweites mal einzuloggen, dann wollen wir, dass die erste Session beendet wird und die zweite Anmeldung Ohne Probleme funktioniert?

**Comment by Til7701** [comment]
Das wäre eine Möglichkeit. Wenn wir den Login nicht erlauben, kann sich ein User bis zum Server-Neustart nicht einloggen, wenn es mal zu einem Problem kommt. 

Wir könnten es auch erlauben, dass ein User sich mit zwei Clients einloggen kann, aber das führt zu sehr vielen Problemen.

Wenn du noch eine Möglichkeit kennst, bin ich dafür offen.

**Comment by JayPi4c** [comment]
Ne, ich finde diese Möglichkeit schon in Ordnung. Wir sparen uns da eine Menge Kopfschmerzen mit simultanen Sessions.
Und wenn ein User Account kompromittiert sein sollte und er erfährt davon, dann kann er sich selbst einloggen, den Hacker damit aus der Session entfernen und selbst das Passwort ändern.
