### ISSUE TITLE
[ISSUE]: Create server internal events

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#81]
Wollen wir serverinterne Events hinzufügen?
Im Moment macht zum Beispiel der [AuthenticationService](https://github.com/schlunzis/Kurtama/blob/96e5341cc87be04c27b1c5ae894c6eadedbf9c7a/server/src/main/java/org/schlunzis/kurtama/server/auth/AuthenticationService.java) beim Einloggen sehr viel. Zusätzlich zum einloggen informiert er den neuen Client über die existierenden Lobbies und schickt eine ChatMessage. Das könnte sehr viel werden, wenn wir noch mehr Ideen haben, wie:

- Statistiken (wie viele Spiele laufen...)
- ServerChatMessages (Basierend auf Ereignissen im Spiel; Lobby verlassen, beigetreten...)

Der Vorschlag wäre, dass wir in solchen Fällen serverinterne Events hinzufügen, welche in den jeweiligen Services (oder sogar extra dafür erstellten Services) abgefangen und verarbeitet werden. Also würde der ChatService die Willkommensnachricht schicken und der LobbyService über die Lobbies informieren.

Ein Problem dabei könnte die Reihenfolge der Nachrichten sein. Wir können die Verantwortung auf den Client schieben, oder im Server eine Struktur aufbauen, welche eine Reihenfolge garantiert.

**Comment by JayPi4c** [comment]
Ich sehe das Problem, dass ein Service nicht alle Sachen bearbeiten kann. Das sollte wirklich nicht so sein und wir sollten uns was dazu überlegen. Ich sehe aber auch ein Problem darin, wenn wir für jede kleine Info eine neue Nachricht an den Client schicken. Das wird zum einen, wie du schon sagst, ein Problem mit der Reihenfolge, zum anderen wird das aber auch sehr schnell viel Overhead an Message Struktur, die wir dann ja jedesmal mitschicken. Ich finde, wir sollten einen Weg finden, wie wir für ein Event vom Client eine Antwort vom Server generieren. Vielleicht gibt es ja ein Pattern für `MessageAssembler` oder sowas. Vielleicht sowas, dass wir von allen Services im Server eine Nachricht zum Assembler schicken und wenn da die Nachricht fertig ist, kann er die zum Client schicken. Das ist jetzt sehr abstrakt gedacht und hat noch viele Lücken, aber generell finde ich das schon besser als tausende Nachrichten an den Client zu spamen.

**Comment by Til7701** [comment]
Ich habe auf einem Branch hier schon mal herumgespielt. Das ist aber noch kein echtes Konzept, und es gibt bestimmt bessere Möglichkeiten.
