### ISSUE TITLE
[BUG]: Exception when no lobby is selected

### ISSUE THREAD

**Issue by Til7701** [schlunzis/Kurtama#89]
### What happened?

An exception is thrown!

### Steps to reproduce

1. Login
2. Don´t select a Lobby
3. Click the "Join Lobby" Button

### Expected behaviour

Nothing should happen.

### Actual behaviour

An Exception is thrown.

(I don´t know, if this is really a bug, or a feature request)

### Further Information

The button should be disabled, if no Lobby is selected.

### Version

1.0-SNAPSHOT

### What OS are you using

Windows

**Comment by JayPi4c** [comment]
Instead of disabling the button, we might also consider to send a notification to the user, that a lobby must be selected in order to join. We may address this when introducing `controlsfx`.
