### ISSUE TITLE
[ISSUE]: Enable Java Virtual Threads

### ISSUE THREAD

**Issue by JayPi4c** [schlunzis/Kurtama#92]
### What is the problem?

Even though we are updated to java 21 and the latest spring boot 3.2.0, we do not use virtual threads in the spring boot backend yet. This might be changed by setting the following property:
`spring.threads.virtual.enabled: true`
This will make spring use virtual threads under the hood.
We might want to update our own backend to use JVT more exhaustively.

**Comment by Til7701** [comment]
I was thinking about processing each request in it's own virtual thread. But we have to change everything to be thread save before we do that.
